import { DataTypesEnum } from "./utils/data-types-enum";
import { CSRestOptions } from "./utils/axios-factory";
import Auth from "./handlers/auth";
import Nodes from "./handlers/nodes";
import Workflow from "./handlers/workflow";
import RHCore from "./handlers/rhcore";
import Search from "./handlers/search";
import Members from "./handlers/members";
import Versions from "./handlers/versions";
import WebReports from "./handlers/webreports";
import RPCClient from "./rpc-client/index";
import { AxiosInstance, AxiosRequestConfig, AxiosResponse } from "axios";
export default class Session {
    protected readonly axios: AxiosInstance;
    protected _nodes: Nodes;
    protected _auth: Auth;
    protected _workflow: any;
    protected _rhcore: RHCore;
    protected _members: Members;
    protected _search: Search;
    protected _webreports: WebReports;
    protected _versions: Versions;
    readonly baseUrl: string;
    constructor(options: CSRestOptions);
    get nodes(): Nodes;
    get auth(): Auth;
    get workflow(): Workflow;
    get rhcore(): RHCore;
    get members(): Members;
    get search(): Search;
    get webreports(): WebReports;
    get versions(): Versions;
    get dataTypesEnum(): typeof DataTypesEnum;
    rpcClient(relativePath?: string): RPCClient;
    _isObject(value: unknown): value is Object;
    _isString(value: unknown): value is string;
    _isBoolean(value: unknown): value is boolean;
    _isFile(value: any): value is File;
    objectToForm(obj: Record<string, any>): any;
    putForm(url: any, params: any): Promise<AxiosResponse<any, any>>;
    postForm(url: any, params: any): Promise<AxiosResponse<any, any>>;
    patchForm(url: any, params: any): Promise<AxiosResponse<any, any>>;
    deleteForm(url: any, params: any): Promise<AxiosResponse<any, any>>;
    putBody(url: any, body: any): Promise<AxiosResponse<any, any>>;
    postBody(url: any, body: any): Promise<AxiosResponse<any, any>>;
    patchBody(url: any, body: any): Promise<AxiosResponse<any, any>>;
    deleteBody(url: any, body: any): Promise<AxiosResponse<any, any>>;
    get<T = any, R = AxiosResponse<T>>(url: string, config?: AxiosRequestConfig): Promise<R>;
    post<T = any, R = AxiosResponse<T>>(url: string, data?: T, config?: AxiosRequestConfig): Promise<R>;
    put<T = any, R = AxiosResponse<T>>(url: string, data?: T, config?: AxiosRequestConfig): Promise<R>;
    patch<T = any, R = AxiosResponse<T>>(url: string, data?: T, config?: AxiosRequestConfig): Promise<R>;
    options<T = any, R = AxiosResponse<T>>(url: string, config?: AxiosRequestConfig): Promise<R>;
    delete<T = any, R = AxiosResponse<T>>(url: string, config?: AxiosRequestConfig): Promise<R>;
    $get<T = any>(url: string, config?: AxiosRequestConfig): Promise<T>;
}
